# Generated by Django 3.0.6 on 2020-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'sale is live '), ('SOLD', 'sale is ended'), ('RESTOCKING', 'sale will be back in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='no issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'sale is live '), ('SOLD', 'sale is ended'), ('RESTOCKING', 'sale will be back in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='no issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'sale is live '), ('SOLD', 'sale is ended'), ('RESTOCKING', 'sale will be back in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='no issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
